language: go

go:
- 1.x
- "1.10"
- 1.11.x
- master


script:
- curl 127.0.0.1:8080/home -X GET && 
- curl 127.0.0.1:8080/api -X GET &&
- curl 127.0.0.1:8080/api -X POST  &&
- curl 127.0.0.1:8080/api -X PUT &&
- curl 127.0.0.1:8080/api -X DELETE